service: kraicklist-api
frameworkVersion: '2'

provider:
  name: aws
  runtime: go1.x
  lambdaHashingVersion: 20201221
  stage: prod
  region: me-south-1
  environment:
    DYNAMODB_TABLE: kraicklist-${opt:stage, self:provider.stage}-products
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
      Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.DYNAMODB_TABLE}"

functions:
  list:
    handler: bin/list
    package:
      include: ./bin/list
    events:
      - httpApi:
          path: /products
          method: get
  search:
    handler: bin/search
    package:
      include: ./bin/search
    events:
      - httpApi:
          path: /search/{q}
          method: get
  get:
    handler: bin/get
    package:
      include: ./bin/get
    events:
      - httpApi:
          path: /products/{id}
          method: get
resources:
  Resources:
    ProductsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.DYNAMODB_TABLE}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: N
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
