service: kraicklist-api
frameworkVersion: '2'

provider:
  name: aws
  runtime: go1.x
  lambdaHashingVersion: 20201221
  stage: prod
  region: me-south-1
  environment:
    DYNAMODB_TABLE: kraicklist-${opt:stage, self:provider.stage}-products
    ELASTICSEARCH_DOMAIN: https://search-kraicklist-kbskg2co6dxfa7ce6dklrnlemm.me-south-1.es.amazonaws.com
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
      Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.DYNAMODB_TABLE}"

functions:
  list:
    handler: bin/list
    package:
      include: ./bin/list
    events:
      - httpApi:
          path: /products
          method: get
  search:
    handler: bin/search
    package:
      include: ./bin/search
    events:
      - httpApi:
          path: /search/{q}
          method: get
  get:
    handler: bin/get
    package:
      include: ./bin/get
    events:
      - httpApi:
          path: /products/{id}
          method: get
resources:
  Resources:
    ProductsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.DYNAMODB_TABLE}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: N
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST

    # ElasticsearchDomain:
    #   Type: AWS::Elasticsearch::Domain
    #   Properties:
    #     DomainName: ${self:provider.environment.ELASTICSEARCH_DOMAIN}
    #     ElasticsearchClusterConfig:
    #       InstanceCount: "1"
    #       ZoneAwarenessEnabled: "true"
    #       InstanceType: "t3.small.elasticsearch"
    #     EBSOptions:s
    #       EBSEnabled: true
    #       VolumeSize: 10
    #       VolumeType: "gp2"
    #     AccessPolicies:
    #       Version: "2012-10-17"
    #       Statement:
    #         -
    #           Effect: "Allow"
    #           Principal:
    #             AWS: "arn:aws:iam::123456789012:user/es-user"
    #           Action: "es:*"
    #           Resource: "arn:aws:es:us-east-1:846973539254:domain/test/*"
    #     AdvancedOptions:
    #       rest.action.multi.allow_explicit_index: "true"